#!/bin/bash
# Author: meepmaster
# Date: 06-05-2022
# Description: Nmap scan


# Color variables 

RED="\033[1;31m"
GREEN="\033[1;32m"
NOCOLOR="\033[0m"

# User root check

function user() {
	if [ $(id -u) != "0" ];then																				# Or like: 
		echo -e "\n${GREEN}Please run this script with root user!${NOCOLOR}"
		exit 1
	fi
}

# Internet connection check

function connect() {
	ping -c 1 -w 3 google.com > /dev/null 2>&1																# Comments...
	if [ "$?" != 0 ];then
		echo -e "\n${RED}[!]${NOCOLOR} ${GREEN}This script needs an active internet connection!${NOCOLOR}"
		exit 1
	fi
}

function app_install () {

# Nmap installation	

	if [ ! -x "$(command -v nmap)" ];then																	# Comments...
        echo -e "${RED}[+]${NOCOLOR} ${GREEN}Nmap not detected...Installing${NOCOLOR}"
        sudo apt-get install nmap -y > installing;rm installing
else
    echo "${GREEN}[+] nmap detected${NOCOLOR}"
     
fi
}

# Nmap open ports

function nmap_ports_open () {
	echo -e "${GREEN}Type IP${NOCOLOR}"
	read ip
	echo -e "${GREEN}Grabbing ports...${NOCOLOR}"
	ports=$(nmap -p- --min-rate 1000 -T4 $ip | grep ^[0-9] | cut -d '/' -f 1 | tr '\n' ',' | sed s/,$//)  	#
	echo -e "${GREEN}Ports grabbed!${NOCOLOR}"
	echo -e "${GREEN}Scanning open ports...${NOCOLOR}"
	nmap -sC -sV -Pn -p $ports $ip																			# -sC
}	

# Call functions

user
connect
app_install
nmap_ports_open